sjfgs
sdflhdsfhsdg
sdghlsdkg
sdgsdg
sdg
sd
g
sdg
[A[Asdgsg[Csg[As[Ag[Asg[Asg[D[B[B[B[Bs[Ddgdg[B[Dg[Ag[Asg[Dg[Ds[B[Ds[Dgs[Dg[Dsg[D[B[B[Bs[Ddg[B[Dsg[D[D[D[D[D[D[D[D[D[D[D[D[D[D[Bg[Asg[Ag[A[D[Dg[Dsg[D[Dsdg[D[D[D[D[Dsdg[D[D[D[D[D[D[D[D[Dsdg[Dsdg[D[D[B[D[Bsg[Bsdg[A[D[D[D[D[D[D[D[D[B[B[B[D[B[B[A